import { randomUUID } from "node:crypto";
import { Pool, type QueryResultRow } from "pg";
import type { Campus, MatchPreference, PreferredSlot, Profile, Schedule, School, User } from "./domain/types.js";
import { now, type CoreStore } from "./store.js";

const toIso = (value: Date | string): string => new Date(value).toISOString();
const profileFromRow = (row: QueryResultRow): Profile => ({ userId: row.user_id, schoolId: row.school_id, campusId: row.campus_id, nickname: row.nickname, major: row.major, grade: row.grade, studentType: row.student_type, activities: row.activities, interests: row.interests, languages: row.languages, updatedAt: toIso(row.updated_at) });
const scheduleFromRow = (row: QueryResultRow): Schedule => ({ id: row.id, userId: row.user_id, dayOfWeek: row.day_of_week, subjectName: row.subject_name, startTime: row.start_time, endTime: row.end_time, classroom: row.classroom, createdAt: toIso(row.created_at), updatedAt: toIso(row.updated_at) });

export class PostgresStore implements CoreStore {
  constructor(private readonly pool: Pool) {}

  async close(): Promise<void> { await this.pool.end(); }
  async ensureUser(userId: string): Promise<User> { const result = await this.pool.query("INSERT INTO users (id) VALUES ($1) ON CONFLICT (id) DO UPDATE SET id = EXCLUDED.id RETURNING id, is_active", [userId]); return { id: result.rows[0].id, isActive: result.rows[0].is_active }; }
  async listSchools(): Promise<School[]> { const result = await this.pool.query("SELECT id, name, is_active FROM schools WHERE is_active = true ORDER BY name"); return result.rows.map((row) => ({ id: row.id, name: row.name, isActive: row.is_active })); }
  async campusesForSchool(schoolId: string): Promise<Campus[]> { const result = await this.pool.query("SELECT id, school_id, name, time_zone, is_active FROM campuses WHERE school_id = $1 AND is_active = true ORDER BY name", [schoolId]); return result.rows.map((row) => ({ id: row.id, schoolId: row.school_id, name: row.name, timeZone: row.time_zone, isActive: row.is_active })); }
  async getSchool(schoolId: string): Promise<School | undefined> { const result = await this.pool.query("SELECT id, name, is_active FROM schools WHERE id = $1 AND is_active = true", [schoolId]); return result.rows[0] ? { id: result.rows[0].id, name: result.rows[0].name, isActive: result.rows[0].is_active } : undefined; }
  async getCampus(campusId: string): Promise<Campus | undefined> { const result = await this.pool.query("SELECT id, school_id, name, time_zone, is_active FROM campuses WHERE id = $1 AND is_active = true", [campusId]); return result.rows[0] ? { id: result.rows[0].id, schoolId: result.rows[0].school_id, name: result.rows[0].name, timeZone: result.rows[0].time_zone, isActive: result.rows[0].is_active } : undefined; }
  async getProfile(userId: string): Promise<Profile | undefined> { const result = await this.pool.query("SELECT * FROM profiles WHERE user_id = $1", [userId]); return result.rows[0] ? profileFromRow(result.rows[0]) : undefined; }
  async saveProfile(profile: Profile): Promise<Profile> { await this.ensureUser(profile.userId); const result = await this.pool.query("INSERT INTO profiles (user_id, school_id, campus_id, nickname, major, grade, student_type, activities, interests, languages, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT (user_id) DO UPDATE SET school_id=EXCLUDED.school_id,campus_id=EXCLUDED.campus_id,nickname=EXCLUDED.nickname,major=EXCLUDED.major,grade=EXCLUDED.grade,student_type=EXCLUDED.student_type,activities=EXCLUDED.activities,interests=EXCLUDED.interests,languages=EXCLUDED.languages,updated_at=EXCLUDED.updated_at RETURNING *", [profile.userId, profile.schoolId, profile.campusId, profile.nickname, profile.major, profile.grade, profile.studentType, profile.activities, profile.interests, profile.languages, profile.updatedAt]); return profileFromRow(result.rows[0]); }
  async nicknameTaken(nickname: string, exceptUserId: string): Promise<boolean> { const result = await this.pool.query("SELECT 1 FROM profiles WHERE nickname = $1 AND user_id <> $2", [nickname, exceptUserId]); return result.rowCount !== 0; }
  async getPreference(userId: string): Promise<MatchPreference> { const result = await this.pool.query("SELECT user_id, is_discoverable, minimum_meeting_minutes, updated_at FROM match_preferences WHERE user_id = $1", [userId]); return result.rows[0] ? { userId, isDiscoverable: result.rows[0].is_discoverable, minimumMeetingMinutes: result.rows[0].minimum_meeting_minutes, updatedAt: toIso(result.rows[0].updated_at) } : { userId, isDiscoverable: true, minimumMeetingMinutes: 60, updatedAt: now() }; }
  async savePreference(preference: MatchPreference): Promise<MatchPreference> { await this.ensureUser(preference.userId); const result = await this.pool.query("INSERT INTO match_preferences (user_id,is_discoverable,minimum_meeting_minutes,updated_at) VALUES ($1,$2,$3,$4) ON CONFLICT (user_id) DO UPDATE SET is_discoverable=EXCLUDED.is_discoverable,minimum_meeting_minutes=EXCLUDED.minimum_meeting_minutes,updated_at=EXCLUDED.updated_at RETURNING *", [preference.userId, preference.isDiscoverable, preference.minimumMeetingMinutes, preference.updatedAt]); const row = result.rows[0]; return { userId: row.user_id, isDiscoverable: row.is_discoverable, minimumMeetingMinutes: row.minimum_meeting_minutes, updatedAt: toIso(row.updated_at) }; }
  async listSchedules(userId: string): Promise<Schedule[]> { const result = await this.pool.query("SELECT * FROM class_schedules WHERE user_id = $1 ORDER BY day_of_week, start_time, id", [userId]); return result.rows.map(scheduleFromRow); }
  async createSchedule(schedule: Omit<Schedule, "id" | "createdAt" | "updatedAt">): Promise<Schedule> { await this.ensureUser(schedule.userId); const timestamp = now(); const result = await this.pool.query("INSERT INTO class_schedules (id,user_id,day_of_week,subject_name,start_time,end_time,classroom,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$8) RETURNING *", [`schedule_${randomUUID()}`, schedule.userId, schedule.dayOfWeek, schedule.subjectName, schedule.startTime, schedule.endTime, schedule.classroom, timestamp]); return scheduleFromRow(result.rows[0]); }
  async updateSchedule(scheduleId: string, update: Partial<Omit<Schedule, "id" | "userId" | "createdAt" | "updatedAt">>): Promise<Schedule | undefined> { const columns = Object.entries(update).map(([key, value], index) => ({ column: ({ dayOfWeek: "day_of_week", subjectName: "subject_name", startTime: "start_time", endTime: "end_time", classroom: "classroom" } as Record<string, string>)[key], value, index })); if (columns.length === 0) { const result = await this.pool.query("SELECT * FROM class_schedules WHERE id=$1", [scheduleId]); return result.rows[0] ? scheduleFromRow(result.rows[0]) : undefined; } const assignments = columns.map(({ column, index }) => `${column} = $${index + 2}`).join(", "); const result = await this.pool.query(`UPDATE class_schedules SET ${assignments}, updated_at = $${columns.length + 2} WHERE id = $1 RETURNING *`, [scheduleId, ...columns.map(({ value }) => value), now()]); return result.rows[0] ? scheduleFromRow(result.rows[0]) : undefined; }
  async deleteSchedule(scheduleId: string): Promise<boolean> { const result = await this.pool.query("DELETE FROM class_schedules WHERE id = $1", [scheduleId]); return result.rowCount === 1; }
  async getAvailability(userId: string): Promise<PreferredSlot[]> { const result = await this.pool.query("SELECT day_of_week, start_time, end_time FROM availability_slots WHERE user_id = $1 ORDER BY day_of_week, start_time", [userId]); return result.rows.map((row) => ({ dayOfWeek: row.day_of_week, startTime: row.start_time, endTime: row.end_time })); }
  async getAvailabilityUpdatedAt(userId: string): Promise<string> { const result = await this.pool.query("SELECT updated_at FROM availability_updates WHERE user_id = $1", [userId]); return result.rows[0] ? toIso(result.rows[0].updated_at) : now(); }
  async saveAvailability(userId: string, slots: PreferredSlot[]): Promise<PreferredSlot[]> { await this.ensureUser(userId); const client = await this.pool.connect(); try { await client.query("BEGIN"); await client.query("DELETE FROM availability_slots WHERE user_id = $1", [userId]); for (const slot of slots) await client.query("INSERT INTO availability_slots (user_id,day_of_week,start_time,end_time) VALUES ($1,$2,$3,$4)", [userId, slot.dayOfWeek, slot.startTime, slot.endTime]); await client.query("INSERT INTO availability_updates (user_id,updated_at) VALUES ($1,$2) ON CONFLICT (user_id) DO UPDATE SET updated_at=EXCLUDED.updated_at", [userId, now()]); await client.query("COMMIT"); return slots; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
  async getUser(userId: string): Promise<User | undefined> { const result = await this.pool.query("SELECT id, is_active FROM users WHERE id = $1", [userId]); return result.rows[0] ? { id: result.rows[0].id, isActive: result.rows[0].is_active } : undefined; }
  async listProfilesAtCampus(campusId: string): Promise<Profile[]> { const result = await this.pool.query("SELECT * FROM profiles WHERE campus_id = $1", [campusId]); return result.rows.map(profileFromRow); }
}

export function createPostgresStore(databaseUrl: string): PostgresStore { return new PostgresStore(new Pool({ connectionString: databaseUrl })); }
